name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex

      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex
          latexmk -c

      - name: Prepare GitHub Pages
        run: |
          mkdir -p public/cv

          cp CV/resume.pdf public/cv/
          cp CV/cvbg.png public/cv/
          cp CV/resume_photo.JPG public/cv/
          
          echo '<!DOCTYPE html>' > public/index.html
          echo '<html><head>' >> public/index.html
          echo '<meta charset="UTF-8">' >> public/index.html
          echo '<title>Resume - Светлов Роман</title>' >> public/index.html
          echo '<meta http-equiv="refresh" content="0; url=cv/resume.pdf">' >> public/index.html
          echo '<script>window.location.href="cv/resume.pdf";</script>' >> public/index.html
          echo '</head><body>' >> public/index.html
          echo '<p>Redirecting to <a href="cv/resume.pdf">resume.pdf</a></p>' >> public/index.html
          echo '</body></html>' >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date +'%Y-%m-%d %H:%M')"
