name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm  # Используем стабильный Debian вместо Fedora

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX (Debian packages)
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            texlive-full \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-xetex \
            lmodern \
            fonts-freefont-otf

      - name: Build PDF
        run: |
          cd CV
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex

      - name: Upload to resume-pdf branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CV
          publish_branch: resume-pdf
          force_orphan: true
          commit_message: "Auto-update: $(date +'%Y-%m-%d %H:%M')"
