name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Full TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex

      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to resume-pdf branch
        run: |
          mkdir -p pdf-deploy
          cp CV/resume.pdf pdf-deploy/
          
          if git clone --branch resume-pdf https://github.com/${{ github.repository }}.git pdf-branch; then
            echo "Branch exists"
          else
            mkdir pdf-branch
            cd pdf-branch
            git init
            git checkout -b resume-pdf
            cd ..
          fi
          
          cp pdf-deploy/resume.pdf pdf-branch/
          cd pdf-branch
          
          git add resume.pdf
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git resume-pdf --force
