name: Build and Deploy Resume PDF
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LaTeX packages
        run: |
          dnf update -y
          dnf install -y \
            texlive-scheme-basic \
            texlive-collection-latexrecommended \
            texlive-fontawesome5 \
            texlive-hyperref \
            texlive-hyphenat

      - name: Build PDF
        run: |
          cd CV
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CV
          publish_branch: resume-pdf
          keep_files: false
          force_orphan: true
          commit_message: "Auto-update resume.pdf [skip ci]"
