name: Build and Deploy Resume PDF
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ALL LaTeX dependencies
        run: |
          dnf update -y
          dnf install -y \
            texlive-scheme-full \
            texlive-wallpaper \
            texlive-geometry \
            texlive-fontawesome5 \
            texlive-hyperref \
            texlive-hyphenat \
            texlive-latexextra \
            texlive-xetex \
            texlive-collection-langcyrillic

      - name: Build PDF (3 passes for references)
        run: |
          cd CV
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex

      - name: Deploy to resume-pdf branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CV
          publish_branch: resume-pdf
          force_orphan: true
          commit_message: "Auto-update: $(date +'%Y-%m-%d %H:%M')"
