name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/cv/resume.pdf

    steps:
      - uses: actions/checkout@v4
        
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex
      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex
          latexmk -c
      - name: Prepare Pages Content
        run: |
          mkdir -p public/cv
          cp CV/resume.pdf public/cv/
          cp CV/cvbg.png public/cv/
          cp CV/resume_photo.JPG public/cv/
          echo "https://${{ github.repository_owner }}.github.io/cv/resume.pdf" > public/url.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
