name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex

      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex
          # Очищаем временные файлы
          latexmk -c

      - name: Prepare clean deployment
        run: |
          mkdir -p deploy
          cp CV/resume.pdf deploy/
          cp CV/cvbg.png deploy/
          cp CV/resume_photo.JPG deploy/
          touch deploy/.nojekyll

      - name: Deploy to resume-pdf branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: resume-pdf
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date +'%Y-%m-%d %H:%M')"
