name: Build Resume PDF
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:31

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          dnf update -y
          dnf install -y \
            texlive-scheme-full \
            texlive-wallpaper \
            texlive-fontawesome5 \
            texlive-hyphenat

      - name: Build PDF
        run: |
          cd CV
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4  # ← Вот это исправление!
        with:
          name: resume.pdf
          path: CV/resume.pdf
