name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex

      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex

      - name: Deploy to resume-pdf branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git clone https://github.com/${{ github.repository }}.git pdf-branch
          cd pdf-branch
          
          git checkout resume-pdf 2>/dev/null || git checkout -b resume-pdf
          
          cp ../CV/resume.pdf .
          
          git add resume.pdf
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git resume-pdf --force
