name: Build and Deploy Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-cyrillic \
            texlive-xetex

      - name: Build PDF
        run: |
          cd CV
          latexmk -pdf -interaction=nonstopmode resume.tex
          latexmk -c

      - name: Prepare GitHub Pages
        run: |
          mkdir -p docs
          cp CV/resume.pdf docs/
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=resume.pdf"></head></html>' > docs/index.html
